
services:
  remi_server:
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    image: remi_server:latest
    env_file: .env
    environment:
      NODE_ENV: production
      PORT: 80
      VIRTUAL_HOST: backend.mrbeas.net
      LETSENCRYPT_HOST: backend.mrbeas.net
      LETSENCRYPT_EMAIL: millionmulugeta09@gmail.com
    expose:
      - "80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    user: "node"
    volumes:
      - /usr/src/app/node_modules
      - /usr/share/nginx/html
    networks:
      - default

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      retries: 5
    networks:
      - default

  nginx-letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-letsencrypt
    environment:
      DEFAULT_EMAIL: millionmulugeta09@gmail.com
      NGINX_PROXY_CONTAINER: nginx-proxy
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    driver: bridge
