
services:
  remi_server:
    container_name: remi_server
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    image: remi_server:latest
    env_file: .env
    environment:
      NODE_ENV: production
      PORT: 80
      VIRTUAL_HOST: backend.mrbeas.net
      VIRTUAL_PORT: 80
      LETSENCRYPT_ENABLED: "true"
      LETSENCRYPT_HOST: backend.mrbeas.net
      LETSENCRYPT_EMAIL: millionmulugeta09@gmail.com
    expose:
      - "80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    user: "node"
    networks:
      - default

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - default

  nginx-letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-letsencrypt
    environment:
      DEFAULT_EMAIL: millionmulugeta09@gmail.com
      NGINX_PROXY_CONTAINER: nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
    restart: unless-stopped
    networks:
      - default

volumes:
  certs:
  vhost:
  html:

networks:
  default:
    driver: bridge
